import { Inter } from "next/font/google";
import "./globals.css";
import { shopifyFetch } from "@/utils/shopify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function getAllProducts() {
  return shopifyFetch({
    query: `{
			products(first: 10) {
				edges {
					node {
						id
						title
						handle
						description
						images(first: 1) {
							edges {
								node {
									originalSrc
									altText
								}
							}
						}
						priceRange {
							minVariantPrice {
								amount
								currencyCode
							}
						}
					}
				}
			}
		}
		`,
  });
}

export default async function RootLayout({ children }) {
  const {
    body: {
      data: { products },
    },
  } = await getAllProducts();

  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        {products.edges.map(({ node }) => (
          <div key={node.id}>
            <h2>{node.title}</h2>
            <p>{node.description}</p>
            <img src={node.images?.edges[0]?.node?.originalSrc} alt={node.images?.edges[0]?.node.altText} />
            <p>
              {node.priceRange.minVariantPrice.amount} {node.priceRange.minVariantPrice.currencyCode}
            </p>
          </div>
        ))}
      </body>
    </html>
  );
}
