import { Inter } from "next/font/google";
import "./globals.css";
import { shopifyFetch } from "@/utils/shopify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function getAllProducts() {
  return shopifyFetch({
    query: `{
			products(first: 10) {
				edges {
					node {
						id
						title
						handle
						description
						images(first: 1) {
							edges {
								node {
									originalSrc
									altText
								}
							}
						}
						priceRange {
							minVariantPrice {
								amount
								currencyCode
							}
						}
					}
				}
			}
		}
		`,
  });
}

export default async function RootLayout({ children }) {
  const products = await getAllProducts();
  console.log(products);
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
